import { IconDefinition } from '@ant-design/icons-angular';
import {
  UserOutline,
  SmileOutline,
  MessageOutline,
  MessageFill,
  ContactsOutline,
  ContactsFill,
  TeamOutline,
  LogoutOutline,
  SettingOutline,
  SearchOutline,
  PlusOutline,
  MinusOutline,
  FolderOutline,
  CoffeeOutline,
  DeleteOutline,
  AndroidOutline,
  EllipsisOutline,
  LeftOutline,
  RollbackOutline,
  EnterOutline,
  UserAddOutline,
} from '@ant-design/icons-angular/icons';

export const homeIcons: IconDefinition[] = [
  UserOutline,
  SmileOutline,
  MessageOutline,
  MessageFill,
  ContactsOutline,
  ContactsFill,
  TeamOutline,
  LogoutOutline,
  SettingOutline,
  SearchOutline,
  PlusOutline,
  MinusOutline,
  FolderOutline,
  CoffeeOutline,
  DeleteOutline,
  AndroidOutline,
  EllipsisOutline,
  LeftOutline,
  RollbackOutline,
  EnterOutline,
  UserAddOutline,
];
